# Generated by Django 4.0.6 on 2022-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description2',
        ),
        migrations.AddField(
            model_name='movie',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_of_movie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_of_movie',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='movie_of_participant',
            field=models.ManyToManyField(blank=True, null=True, to='todos.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='todos.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
