# Generated by Django 4.0.6 on 2022-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_movie_description2_movie_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='movie_of_participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='Movie',
            field=models.ManyToManyField(blank=True, to='todos.movie'),
        ),
    ]
