# Generated by Django 4.0.6 on 2022-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='todos.tag'),
        ),
    ]
