# Generated by Django 4.0.6 on 2022-08-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_tag_remove_movie_participants_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='todos.participant'),
        ),
    ]
