# Generated by Django 4.0.6 on 2022-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_tag_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todos.tag'),
        ),
    ]
