# Generated by Django 4.0.6 on 2022-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.AddField(
            model_name='movie',
            name='Tag',
            field=models.ManyToManyField(blank=True, null=True, to='todos.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='Movie',
            field=models.ManyToManyField(blank=True, to='todos.movie'),
        ),
    ]
