# Generated by Django 4.0.6 on 2022-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_movie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('title', models.ManyToManyField(null=True, to='todos.title')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='participant',
            field=models.ManyToManyField(null=True, to='todos.participant'),
        ),
    ]
