# Generated by Django 4.0.6 on 2022-08-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_participant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='date_of_birth',
        ),
    ]
