# Generated by Django 4.0.6 on 2022-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_remove_participant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='title',
            field=models.ManyToManyField(null=True, to='todos.title'),
        ),
    ]
