# Generated by Django 4.0.6 on 2022-08-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_participant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='title',
        ),
        migrations.AddField(
            model_name='participant',
            name='titles',
            field=models.ManyToManyField(to='todos.title'),
        ),
    ]
