# Generated by Django 4.0.6 on 2022-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_language_programmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='titles',
        ),
        migrations.AddField(
            model_name='participant',
            name='titles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.title'),
            preserve_default=False,
        ),
    ]
