# Generated by Django 4.0.6 on 2022-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_remove_participant_titles_participant_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='participants',
            field=models.ManyToManyField(to='todos.participant'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='todos.tag'),
        ),
    ]
