# Generated by Django 4.0.6 on 2022-08-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_alter_movie_participants_alter_movie_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tags',
            new_name='tag',
        ),
    ]
