# Generated by Django 4.0.6 on 2022-08-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_rename_tags_movie_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='participants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.participant'),
            preserve_default=False,
        ),
    ]
