# Generated by Django 4.0.6 on 2022-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_remove_programmer_language_delete_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
