# Generated by Django 4.0.6 on 2022-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0020_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
