# Generated by Django 4.0.6 on 2022-08-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_tag_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='video',
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.tag')),
            ],
        ),
    ]
