# Generated by Django 4.0.6 on 2022-08-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0022_remove_tag_image_remove_tag_video_tagimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagimage',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(related_name='tags', to='todos.tagimage'),
        ),
    ]
