# Generated by Django 4.0.6 on 2022-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0025_remove_tag_image_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='todos.tagimage'),
        ),
    ]
