# Generated by Django 4.0.6 on 2022-08-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0027_remove_tag_images_remove_tagimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tagimage',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.tagimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
