# Generated by Django 4.0.6 on 2022-08-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0028_remove_tagimage_images_remove_tagimage_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagimage',
            old_name='image',
            new_name='images',
        ),
    ]
