# Generated by Django 4.0.6 on 2022-08-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0031_alter_tag_slike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagimage',
            old_name='images',
            new_name='image',
        ),
    ]
