# Generated by Django 4.0.6 on 2022-08-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0033_tag1_tagimage1_remove_movie_tag_delete_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TagImage12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tag1',
        ),
        migrations.DeleteModel(
            name='TagImage1',
        ),
        migrations.AddField(
            model_name='tag12',
            name='slike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.tagimage12'),
        ),
    ]
