# Generated by Django 4.0.6 on 2022-08-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0034_tag12_tagimage12_delete_tag1_delete_tagimage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrikazSlika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slikaJedna', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tag12',
        ),
        migrations.DeleteModel(
            name='TagImage12',
        ),
        migrations.AddField(
            model_name='prikazslika',
            name='slike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.slike'),
        ),
    ]
