# Generated by Django 4.0.6 on 2022-08-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0036_alter_slike_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prikazslika',
            name='slike',
        ),
        migrations.AddField(
            model_name='prikazslika',
            name='slike',
            field=models.ManyToManyField(blank=True, null=True, to='todos.slike'),
        ),
    ]
