# Generated by Django 4.0.6 on 2022-08-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0038_remove_prikazslika_slike_remove_slike_slikajedna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prikazslika',
            name='album',
        ),
    ]
