# Generated by Django 4.0.6 on 2022-08-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0039_remove_prikazslika_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='titles',
        ),
    ]
