# Generated by Django 4.0.6 on 2022-08-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0040_remove_participant_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='titles',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todos.title'),
            preserve_default=False,
        ),
    ]
