# Generated by Django 4.0.6 on 2022-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0041_remove_title_participants_participant_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='titles',
        ),
        migrations.AddField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='image_of_participant',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
